# setup.cfg
[metadata]
name = quantum-analyzer
version = 1.0
author = heanczko311299
description = Quantum Analyzer
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/heanczko311299/quantum-analyzer
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    colorama>=0.4.6
    cryptolyzer>=0.10.0
    tabulate>=0.9.0

[options.entry_points]
console_scripts =
    quantum = quantum:main
